# Site settings
title: Kwok Hendrik Wijaya
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kwok Hendrik Wijaya
user_description: I'm a Cloud Architect
user_title: Cloud Architect
email: kwok.hendrik.wijaya@gmail.com

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
